[tool.poetry]
name = "aws-bedrock-handson"
version = "0.1.0"
description = ""
authors = ["yuichkun <yuichkun@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.34.139"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
